### ISSUE TITLE
Should support py3.4

### ISSUE THREAD

**Issue by richardjgowers** [conda-forge/mdanalysis-feedstock#11]
It looks like we're not building for py3.4 currently, but we should be

**Comment by kain88-de** [comment]
python 3.4 is not supported by conda-forge. Only the last two stable releases.  Our dependencies are built on python 3.4 because I ask nicely, so we can keep testing on python 3.4 to support pip builds on older platforms. I'm wouldn't bet that the dependencies are all using the current stable version on python 3.4
